### ISSUE TITLE
[Feature Request] Add option to block telemetry and prevent server been listed on Community-Server list

### ISSUE THREAD

**Issue by miaulightouch** [jammsen/docker-palworld-dedicated-server#108]
### Have you read the Important information text above

- [X] Yes i did

### Describe the feature

even we didn't add "EpicApp=PalServer", server would be listed on server list.

My server was unlisted from server list after I blocked these host:
- api.epicgames.dev
- telemetry.palworldgame.com
- api.palworldgame.com

Currently I add these line to my docker compose:
```yaml
    extra_hosts:
      - api.epicgames.dev:127.0.0.1
      - telemetry.palworldgame.com:127.0.0.1
      - api.palworldgame.com:127.0.0.1
```

But it would be nice if it's became an option for this docker image.

### Additional information

- [ ] Would you be willing to help implement this feature?

### Final checks

- [X] I understand that this is a feature request function. I also unterstand that if i use this to report a bug report, that my issue might be un-answered closed.

**Comment by masonen** [comment]
Interesting that this works - when i tried this the server crashed regularly with an unhandled exception. 

My current assumption was, that this is because they dont handle failed/unanswered calls to the telemetry endpoint correctly.

IF this tuns stable i would see this as a valuable addition

**Comment by miaulightouch** [comment]
> Interesting that this works - when i tried this the server crashed regularly with an unhandled exception.
> 
> My current assumption was, that this is because they dont handle failed/unanswered calls to the telemetry endpoint correctly.
> 
> IF this tuns stable i would see this as a valuable addition

That's weird, creating a new server or importing a save from an existing server doesn't result in any crashes.

**Comment by miaulightouch** [comment]
here's my docker-compose.yaml

```yaml
services:
  palworld-dedicated-server:
    container_name: palworld-dedicated-server
    image: jammsen/palworld-dedicated-server:latest
    restart: always
    ports:
      - 8211:8211/udp
      - 20715:20715/udp
    environment:
      - ALWAYS_UPDATE_ON_START=true
      - SERVER_NAME=test
      - SERVER_DESCRIPTION=
      - ADMIN_PASSWORD=pal
      - SERVER_PASSWORD=
    memswap_limit: -1
    extra_hosts:
      - api.epicgames.dev:127.0.0.1
      - telemetry.palworldgame.com:127.0.0.1
      - api.palworldgame.com:127.0.0.1
```
