### ISSUE TITLE
[Feature Request] [ RFC ] Splitting docker compose from .env 

### ISSUE THREAD

**Issue by Gornoka** [jammsen/docker-palworld-dedicated-server#109]
### Have you read the Important information text above

- [X] Yes i did

### Describe the feature

I think it would make sense to split the docker-compose files from the main readme to reduce the chance of merge conflicts.

Taking this idea one step further would be to move the environment configuration to another file as well so that both compose files/sections in the main readme would not need to be updated simultaniously whenever one of them changes.

### Additional information

- [X] Would you be willing to help implement this feature?

### Final checks

- [X] I understand that this is a feature request function. I also unterstand that if i use this to report a bug report, that my issue might be un-answered closed.

**Comment by jammsen** [comment]
Hey @Gornoka 
I know what you are talking about, that repo had earlier docker-compose.yml and i even had plans to add an .env.example to it, but then i realized i had to always manage docker-compose defintions when we want to integrate "Standalone, Server+Rcon, Server+Rcon for Portainer" and so on. Now you dont have 1 file to manage. But now you have many files to manage and the possibility gets greater to miss something. Thats why i did choose to follow the "fat" readme way. Hope you understand what i mean.

But im open to feedback, what thoughst and alternatives are there to consider?

**Comment by masonen** [comment]
I would suggest the folowing

Everything that is in the env vars of the docker compose files currently goes to a .env.default  (or similar)

in your docker compose files you load this env file via 

```yaml
version: '3.9'
services:
  palworld-dedicated-server:
    #build: .
    container_name: palworld-dedicated-server
    image: jammsen/palworld-dedicated-server:latest
    env_file:
      - path: ./.env.defaul
        required: true
      - path: ./.env.override
        required: false
```

Then ask the user copy the default env file and maybe also provide a script to update the env file in case env vars will get added in the future. 

If the user wants to override any of the default variables they can add them to the override file. 

Possible extenstions: provide a bash script that automatically updates the default env file and maybe a make command that first updates the env file and after that starts the service for full convienience and ensuring that the env file keeps up to date with the latest release. 

This wil drastically reduce the need of solving merge conflicts. Furthermore it will shring down and ease the compose files.
