### ISSUE TITLE
[Bug Report] RCON config file doesn't update from docker env variables

### ISSUE THREAD

**Issue by JPL4494** [jammsen/docker-palworld-dedicated-server#156]
### Have you read the Important information text above

- [X] Yes i did

### Current behavior

Using the latest few images, I am seeing this error in the logs

```
time="2024-01-31T09:00:05-08:00" level=info msg="cli: execute: auth: rcon: dial tcp: address tcp/###RCON_PORT###: unknown port" channel=stderr iteration=0 job.command=/backupmanager.sh job.position=0 job.schedule="0 * * *
```

I'm also getting the same errors when I run it via command line within the container

### Desired behavior

The startup scripts replace the placeholder values with the environment variables if the RCON functionality is enabled

### To Reproduce

1. Run latest image in docker with `RCON_ENABLED` set to `true`
2. Wait for the container to startup
3. Look at logs and see errors

### Software setup

- OS: Ubuntu
- Docker: Docker version 25.0.1, build 29cf629

### Hardware setup

- vCPU: unrestricted
- RAM: unrestricted
- Disk: unrestricted

### Additional context

I replaced the values manually to see if it works, but now I am getting a connection refused error, so I'm not sure if there are other errors?

**Comment by jammsen** [comment]
Hey @JPL4494 
Please share your default.env and your docker-compose.yml with me.
Make sure the passwords are redacted and post it in a code-block please.

**Comment by JPL4494** [comment]
`docker-compose.yml`

```
version: "3.9"

name: games

###########################
#    EXTENSION  FIELDS    #
###########################

# Common environment values
x-environment: &default-environment
  TZ: $TIMEZONE
  PUID: $PUID
  PGID: $PGID
  UMASK: $UMASK

# Keys common to some of the dependent services/apps
x-common-keys: &common-keys
  restart: unless-stopped

services:
  palworld:
    image: jammsen/palworld-dedicated-server:latest
    container_name: palworld
    <<: *common-keys
    ports:
      - target: 8211 # Gamerserver port inside of the container
        published: ${PALWORD_SERVER_PORT:?err} # Gamerserver port on your host
        protocol: udp
        mode: host
      - target: 25575 # RCON port inside of the container
        published: ${PALWORD_RCON_PORT:?err} # RCON port on your host
        protocol: tcp
        mode: host
    environment:
      <<: *default-environment
      PUBLIC_IP: ${PUBLIC_IP:?err}
      COOP_PLAYER_MAX_NUM: 16
      MAX_PLAYERS: 16
      SERVER_NAME: Cristians_Fantasy
      SERVER_DESCRIPTION: For our lovely little man
      SERVER_PASSWORD: ${PALWORD_GAME_PASSWORD:?err}
      ADMIN_PASSWORD: ${PALWORD_ADMIN_PASSWORD:?err}
      RCON_PORT: 25575
      RCON_ENABLED: true
      COMMUNITY_SERVER: false
      BACKUP_RETENTION_POLICY: true
      BACKUP_RETENTION_AMOUNT_TO_KEEP: 7
      # Game settings
      BUILD_OBJECT_DETERIORATION_DAMAGE_RATE: 0.0
      DEATH_PENALTY: None
      PAL_EGG_DEFAULT_HATCHING_TIME: 0.5
      PAL_CAPTURE_RATE: 1.3
      PAL_SPAWN_NUM_RATE: 1.3
      PAL_STOMACH_DECREACE_RATE: 0.0
      PAL_AUTO_HP_REGENE_RATE_IN_SLEEP: 10
      BASE_CAMP_WORKER_MAXNUM: 20
    volumes:
       - ${FOLDER_FOR_GAME:?err}/palworld:/palworld
       - ${FOLDER_FOR_CONFIGS:?err}/palworld/rcon.yml:/home/steam/steamcmd/rcon.yaml
```

`.env`
```
PALWORD_SERVER_PORT=8211
PALWORD_RCON_PORT=25575
PALWORD_GAME_PASSWORD=some-pass
PALWORD_ADMIN_PASSWORD=another-pass
FOLDER_FOR_GAME=path/to/files
FOLDER_FOR_CONFIGS=another/path/to/files
```

**Comment by k997** [comment]
same error
### docker-compose.yaml
```yaml
version: '3.9'
services:
  palworld-dedicated-server:
    build: .
    container_name: palworld-dedicated-server
    image: jammsen/palworld-dedicated-server:latest
    restart: always
    network_mode: bridge
    ports:
      - target: 8211 # Gamerserver port inside of the container
        published: 8211 # Gamerserver port on your host
        protocol: udp
        mode: host
      - target: 25575 # RCON port inside of the container
        published: 25575 # RCON port on your host
        protocol: tcp
        mode: host
    environment:
      # server config
      - ALWAYS_UPDATE_ON_START=true
      - MAX_PLAYERS=32
      - MULTITHREAD_ENABLED=true
      - COMMUNITY_SERVER=false
      - PUBLIC_IP=0.0.0.0
      - PUBLIC_PORT=8211
      - SERVER_NAME=palworld
      - SERVER_DESCRIPTION=Palworld-Dedicated-Server running in Docker by jammsen
      - SERVER_PASSWORD=None
      - BACKUP_ENABLED=true
      - BACKUP_CRON_EXPRESSION=*/15 * * * *
      # game config
      - PAL_EGG_DEFAULT_HATCHING_TIME=0.000000
      - BUILD_OBJECT_DETERIORATION_DAMAGE_RATE=0.000000
      # rcon
      - RCON_ENABLED=true
      - RCON_PORT=25575
      - ADMIN_PASSWORD=<admin_password>
    volumes:
      - $DOCKER_DATA/palworld:/palworld
```

### error log
```
palworld-dedicated-server  | time="2024-02-01T12:00:00+08:00" level=info msg=starting iteration=0 job.command=/backupmanager.sh job.position=0 job.schedule="*/15 * * * *"
palworld-dedicated-server  | time="2024-02-01T12:00:00+08:00" level=info msg="cli: execute: auth: rcon: dial tcp: address tcp/###RCON_PORT###: unknown port" channel=stderr iteration=0 job.command=/backupmanager.sh job.position=0 job.schedule="*/15 * * * *"
palworld-dedicated-server  | time="2024-02-01T12:00:05+08:00" level=info msg="cli: execute: auth: rcon: dial tcp: address tcp/###RCON_PORT###: unknown port" channel=stderr iteration=0 job.command=/backupmanager.sh job.position=0 job.schedule="*/15 * * * *"
palworld-dedicated-server  | time="2024-02-01T12:00:05+08:00" level=info msg="cli: execute: auth: rcon: dial tcp: address tcp/###RCON_PORT###: unknown port" channel=stderr iteration=0 job.command=/backupmanager.sh job.position=0 job.schedule="*/15 * * * *"
palworld-dedicated-server  | time="2024-02-01T12:00:06+08:00" level=info msg="cli: execute: auth: rcon: dial tcp: address tcp/###RCON_PORT###: unknown port" channel=stderr iteration=0 job.command=/backupmanager.sh job.position=0 job.schedule="*/15 * * * *"
palworld-dedicated-server  | time="2024-02-01T12:00:06+08:00" level=info msg="cli: execute: auth: rcon: dial tcp: address tcp/###RCON_PORT###: unknown port" channel=stderr iteration=0 job.command=/backupmanager.sh job.position=0 job.schedule="*/15 * * * *"
```
