### ISSUE TITLE
[Bug Report] Backups Are Not Running

### ISSUE THREAD

**Issue by wwalker0307** [jammsen/docker-palworld-dedicated-server#167]
### Have you read the Important information text above

- [X] Yes i did

### Current behavior

Backups are not running, I have the following settings configured:
```
- BACKUP_ENABLED=true
- BACKUP_CRON_EXPRESSION=0 * * * *
```

### Desired behavior

Backups run

### To Reproduce

Here's my docker-compose
```
services:
  palworld-dedicated-server:
    build: .
    container_name: palworld-dedicated-server
    image: jammsen/palworld-dedicated-server:latest
    restart: always
    network_mode: bridge
    ports:
      - target: 8211 # gamerserver port inside of the container
        published: 8211 # gamerserver port on your host
        protocol: udp
        mode: host
      - target: 25575 # rcon port inside of the container
        published: 25575 # rcon port on your host
        protocol: tcp
        mode: host
    environment:
      - ALWAYS_UPDATE_ON_START=true
      - MAX_PLAYERS=64
      - MULTITHREAD_ENABLED=true
      - COMMUNITY_SERVER=true
      - RCON_ENABLED=true
      - SERVER_NAME=Pals
      - SERVER_DESCRIPTION=Just Another PalWorld
      - EpicApp=PalServer
      - BACKUP_ENABLED=true
      - BACKUP_CRON_EXPRESSION=0 * * * *
      - REGION=NA
    volumes:
      - ./game:/palworld
  rcon:
    image: outdead/rcon:latest
    profiles: ['rcon']
```

### Software setup

- OS: Ubuntu 22.04
- Docker: version 25.0

### Hardware setup

- vCPU: 6
- RAM: 32GB
- Disk: 100GB
