### ISSUE TITLE
RCON is possible, maybe add the ports to expose it?

### ISSUE THREAD

**Issue by Khyretos** [jammsen/docker-palworld-dedicated-server#18]
### Have you read the Important information text above

- [X] Yes i did

### Current behavior

I can enable the RCON in the server if i expose the port, maybe it could be added to the docker-compose.yml?

### Desired behavior

Add it either to the description of the repo or the docker-compose file it could be usefull for other people.

### Links to screenshots

![image](https://github.com/jammsen/docker-palworld-dedicated-server/assets/25864917/6c82b2fd-839a-4bb1-be11-22a69703462e)

### To Reproduce

- Add this to the docker compose file:
```yaml
    ports:
      - "25575:25575/udp"
      - "25575:25575/tcp"
```
- enable `RCONEnabled=True` and setup a port in `RCONPort=25575` in the `/game/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini`  

You wil need a way to connect to the RCON of the game. i use: https://github.com/gorcon/rcon-cli

### Software setup

- OS: Ubuntu 22.04 LTS
- Docker:  Docker version 25.0.0, build e758fe5

### Hardware setup

- vCPU: Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz
- RAM:  16GB
- Disk: 500GB

**Comment by jammsen** [comment]
Hey @Khyretos 
Sure thats easy and no problem at all. 
Are you available on Discord or Teaspeak for a few questions?

**Comment by Khyretos** [comment]
> Hey @Khyretos Sure thats easy and no problem at all. Are you available on Discord or Teaspeak for a few questions?

Discord Khyretos#5151

**Comment by jammsen** [comment]
Added you, feel free to call me

**Comment by uncaught** [comment]
Might even be nice to add `outdead/rcon` as a service to the docker-compose.yml, too.

```yaml
services:
  palworld-dedicated-server:
    ports:
      # ...
      - "25575:25575/udp"
      - "25575:25575/tcp"

    environment:
      # ...
      - ADMIN_PASSWORD=THE_ADMIN_PASSWORD_AS_ABOVE
    #...

  rcon:
    image: outdead/rcon:latest
    entrypoint: ['/rcon', '-a', 'palworld-dedicated-server:25575', '-p', 'THE_ADMIN_PASSWORD_AS_ABOVE']
    profiles: ['rcon'] # prevents booting up with `docker compose up`
```

Usage: `docker compose run --rm rcon ShowPlayers`
