### ISSUE TITLE
[Bug Report] docker compose does not install from steam cmd if folder exists

### ISSUE THREAD

**Issue by brandonnorsworthy** [jammsen/docker-palworld-dedicated-server#196]
### Have you read the Important information text above

- [X] Yes i did

### Current behavior

[Bug Report] docker compose does not install from steam cmd if folder exists, I composed the image to move it to a new computer.

I stopped it for a minute after the steamcmd started and then stopped it for my own reasons, deleted the contents of the mount folder leaving /game existing. This lead to me composing the container again but it wouldnt install.

### Desired behavior

Should install the game server on creation

### To Reproduce

1. Go to compose container
2. Stop container before server installs or possibly even after finished installation
3. Delete contents of mount folder but leave the folder
4. See errors of servermanager looking for the palserver.sh file instead of reinstalling server

### Software setup

- OS: Windows
- Docker: Docker Desktop?

### Hardware setup

- vCPU: 8core
- RAM: 16gb
- Disk: 1tb

**Comment by brandonnorsworthy** [comment]
After attempts of resolution I just deleted the container, deleted the mount folder it creates on compose `/game` and then composed the container again and it reinstalled steamcmd and the server files

**Comment by brandonnorsworthy** [comment]
Heres my compose
```yml
version: '3.9'
services:
  palworld-dedicated-server:
    #build: .
    container_name: palworld-dedicated-server
    image: jammsen/palworld-dedicated-server:latest
    restart: always
    network_mode: bridge
    ports:
      - target: 8211 # gamerserver port inside of the container
        published: 8211 # gamerserver port on your host
        protocol: udp
        mode: host
      - target: 25575 # rcon port inside of the container
        published: 25575 # rcon port on your host
        protocol: tcp
        mode: host
    environment:
      - ALWAYS_UPDATE_ON_START=true
      - MAX_PLAYERS=32
      - MULTITHREAD_ENABLED=true
      - COMMUNITY_SERVER=true
      - RCON_ENABLED=false
      - RCON_PORT=25575
      - PUBLIC_IP=private
      - PUBLIC_PORT=8211
      - SERVER_NAME=private
      - SERVER_DESCRIPTION=private
      - SERVER_PASSWORD=private
      - ADMIN_PASSWORD=private
      - BACKUP_ENABLED=true
      - BACKUP_CRON_EXPRESSION=0 * * * *
    volumes:
      - ./game:/palworld
      ```
