### ISSUE TITLE
Please provide a unique docker tag:

### ISSUE THREAD

**Issue by jseiser** [jammsen/docker-palworld-dedicated-server#23]
### Have you read the Important information text above

- [X] Yes i did

### Current behavior

You tag everything `latest` which makes pulling new images harder than it needs to be

### Desired behavior

Every time you push to dockerhub there should be a unique tag.

### To Reproduce

1. [Docker Hub](https://hub.docker.com/r/jammsen/palworld-dedicated-server/tags)

### Software setup

- OS: Kubernetes

### Hardware setup

A bunch of nodes

### Additional context

https://medium.com/@mccode/the-misunderstood-docker-tag-latest-af3babfd6375

In short, if you are re-using the `latest` tag, my system has no idea it should be pulling a newer image.  If you do not want to look into versioning, just including the git short sha or something would make pulling the image easier.

Thanks.

**Comment by jseiser** [comment]
You could do something like..


```
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            jammsen/palworld-dedicated-server         
          # generate Docker tags based on the following events/attributes
          tags: |
            type=sha  
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
```

**Comment by jammsen** [comment]
Hey @jseiser im about 75% sure what you mean, are you able to talk with me in Discord or Teamspeak to clear a few of my questions?

**Comment by pchang388** [comment]
From other projects I've seen, you can accomplish this by triggering a build on tag pushes.

```
git tag v1.X.X

git push origin --tags
```

Then in your github ci, you can have something that triggers on tag creations

```yaml
---
name: Create Official Release and Push Artifacts

on:
  push:
    tags:
      - v*

```

And then use the docker-meta action to create a tagged release and a latest if preferred
```yaml
- name: Docker meta
    id: meta
    uses: docker/metadata-action@v5
    with:
      images: docker.io/${{ github.repository }}
      flavor: |
        latest=${{ fromJSON(inputs.latest) }}
      # for some reason can't get this to show up from docker image labels
      # placing here for now
      labels: |
        org.opencontainers.image.description=Prometheus exporter for tdarr
      tags: |
        ## add the event types that should be added as tags
        ## on release - for use by users
        type=semver,pattern={{major}}.{{minor}}
```

Then you can use the docker-build action to create the new image with `latest` and semantic versioning tag
```yaml
- name: Build Docker Image
    if: github.event_name != 'pull_request'
    uses: docker/build-push-action@v5
    with:
      context: .
      file: ./Dockerfile
      platforms: linux/amd64,linux/arm64
      push: ${{ fromJSON(inputs.push) }}
      tags: ${{ steps.meta.outputs.tags }}
      labels: ${{ steps.meta.outputs.labels }}
      build-args: |
        VERSION=${{ steps.meta.outputs.version }}
        BUILDTIME=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.created'] }}
        REVISION=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.revision'] }}
```

I've seen a similar pattern in other projects and added it to my own here as a reference: https://github.com/homeylab/tdarr-exporter/blob/main/.github/actions/docker/action.yml
