### ISSUE TITLE
[Feature Request] Update Docker Hub Readme on CI-push

### ISSUE THREAD

**Issue by jammsen** [jammsen/docker-palworld-dedicated-server#28]
### Have you read the Important information text above

- [X] Yes i did

### Current behavior

I have to copy paste manually every change i do in the readme.md here to publish it to docker-hub

### Desired behavior

A Github Actions CI-solution updates the readme on docker-hub from here.

### Software setup

- OS:
- Docker:

### Hardware setup

- vCPU: 
- RAM: 
- Disk:

**Comment by pchang388** [comment]
Hey thanks for the image, I actually do something similar with another project I wrote. You can use a github action for this

```yaml
- name: Update Dockerhub Documentation
    uses: peter-evans/dockerhub-description@v3
    if: ${{ (fromJSON(inputs.latest) == true) && (github.event_name != 'pull_request') }}
    with:
      username: ${{ inputs.dockerhub_username }}
      password: ${{ inputs.dockerhub_token }}
      repository: ${{ github.repository }}
```

I can also open a PR when I get some time but username/password come from my inputs which are `environment secrets` in the repo settings. Hope this helps!
