### ISSUE TITLE
[Question] Accessing RCON via Portainer

### ISSUE THREAD

**Issue by Plarpoon** [jammsen/docker-palworld-dedicated-server#31]
I don't really know if this is the right place to ask but I am running your docker-compose image on Portainer. I cannot seem to easily access the RCON from there tho. Anyone else that had the same idea that knows how to do that?

It's not hard to access the inside of the container, I just don't know how to access the RCON itself from there, see below.
![image](https://github.com/jammsen/docker-palworld-dedicated-server/assets/40299833/2cc5aec0-5c5b-4a6f-aeee-0447e7ce4b96)

**Comment by Plarpoon** [comment]
Hi @ComputersWithTimo, unfortunately that README did not help me much but I found out what the issue was. Opening a PR so everyone can benefit from the changes I made, thank you a lot regardless!

**Comment by uncaught** [comment]
I still think you should run rcon in the same network and just use the palworld-server's service name as host for rcon. It runs for me perfectly without the hassle:

```yml
services:
  palworld:
    image: jammsen/palworld-dedicated-server:latest
    ports:
      - "8211:8211/udp"
      - "25575:25575/udp"
      - "25575:25575/tcp"
    environment:
      - ALWAYS_UPDATE_ON_START=true
      - MAX_PLAYERS=32
      - MULTITHREAD_ENABLED=true
      - COMMUNITY_SERVER=false
      - PUBLIC_IP=xxx-my-public-ip-xxx
      - PUBLIC_PORT=8211
      - SERVER_NAME=xxx
      - SERVER_DESCRIPTION=xxx
      - SERVER_PASSWORD=xxx
      - ADMIN_PASSWORD=xxx
    volumes:
      - ./game:/palworld
    deploy:
      resources:
        limits:
          memory: 10G

  rcon:
    image: outdead/rcon:latest
    entrypoint: ['/rcon', '-a', 'palworld:25575', '-p', 'xxx']
    profiles: ['rcon'] # prevents booting up with `docker compose up`
```

(The memory limit is of course only temporary until they fix that damn leak.)
