### ISSUE TITLE
[Help] Cant run the RCON commands at all

### ISSUE THREAD

**Issue by andarilhoz** [jammsen/docker-palworld-dedicated-server#59]
### Have you read the Important information text above

- [X] Yes i did

### Current behavior

With the README.md dockerfile, when i try to run `sudo docker-compose run --rm rcon info` i got the following log:

```bash
cli: execute: auth: rcon: dial tcp 10.0.0.5:25575: i/o timeout
ERROR: 1
```

I dont know much about the rcon, but shouldnt the ip(10.0.0.5) be somehow a link to the palworld container?

### Desired behavior

When running the RCON info command, receive the rcon info feedback

### Links to screenshots

![image](https://github.com/jammsen/docker-palworld-dedicated-server/assets/7517587/dc12324e-30b7-405b-9ebd-b0e3532b251f)

### To Reproduce

1. Use the docker-compose.yml with rcon example
2. do the `docker-compose up -d`
3. execute the command: `$ docker-compose run --rm rcon info`
4. See the log

### Software setup

- OS: Ubuntu Server 22.04
- Docker: 25.0.1

### Hardware setup

- vCPU:  4
- RAM:  16
- Disk: 60

I'm currently using the aws ec2 t3a.xlarge

**Comment by jammsen** [comment]
Hey @andarilhoz - Yes 🤣 you have to insert your own IP of your docker-node to able to use that. 
10.0.05 is just my default im commiting for my delevopment 😎 
You could also rework the docker-compose in the network section and use the service-name as the "alias" for the ip.

Up to you 👍

**Comment by andarilhoz** [comment]
Thank you! i just added a new network to make a bridge betweeen both containers and it worked, if anyone else in the future had the same problem and find this comment, this is my docker-compose:

```yml
version: '3.9'
services:
  palworld-dedicated-server:
    build: .
    container_name: palworld-dedicated-server
    image: jammsen/palworld-dedicated-server:latest
    restart: unless-stopped
    ports:
      - "8211:8211/udp"
      - "25575:25575/tcp"
      - "25575:25575/udp" 
    environment:
      - ALWAYS_UPDATE_ON_START=true
      - MAX_PLAYERS=32
      - MULTITHREAD_ENABLED=true
      - COMMUNITY_SERVER=true
      - RCON_ENABLED=true
      - RCON_PORT=25575
      - PUBLIC_IP=10.0.0.5
      - PUBLIC_PORT=8211
      - SERVER_NAME=myservername
      - SERVER_DESCRIPTION=mygameserver
      - SERVER_PASSWORD=mypassword
      - ADMIN_PASSWORD=adminPasswordHere
      - BACKUP_ENABLED=true
      - BACKUP_CRON_EXPRESSION=0 * * * *
    volumes:
      - ./game:/palworld
    networks:
      - palworld-network

  rcon:
    image: outdead/rcon:latest
    container_name: palworld-rcon
    restart: unless-stopped
    entrypoint: ['/rcon', '-a', 'palworld-dedicated-server:25575', '-p', 'adminPasswordHere']
    tty: true
    stdin_open: true
    depends_on:
      - palworld-dedicated-server
    networks:
      - palworld-network
    profiles: ['rcon']

networks:
  palworld-network:
    driver: bridge

```
