### ISSUE TITLE
[Feature Request] Auto-restart

### ISSUE THREAD

**Issue by MeteorSkyOne** [jammsen/docker-palworld-dedicated-server#71]
### Have you read the Important information text above

- [X] Yes i did

### Describe the feature

This game server has a giant memory leak that all my server memory is occupied, so I need to restart server like every 3-4 hours. So can we support this auto-restart feature to keep server running stably?

### Additional information

- [ ] Would you be willing to help implement this feature?

### Final checks

- [X] I understand that this is a feature request function. I also unterstand that if i use this to report a bug report, that my issue might be un-answered closed.

**Comment by Wistelle** [comment]
You can try adding a line to crontab like

`0 0,6,12,18 * * * docker compose -f <your compose file location> restart`

This command makes it restart at 6am/pm and 12am/pm.
Use a crontab generator(https://crontab.guru/) to figure out your frequency

**Comment by patriq** [comment]
Here's some a gist of a shell script that does it and announces it via RCON: https://gist.github.com/Bluefissure/b0fcb05c024ee60cad4e23eb55463062

**Comment by jammsen** [comment]
> Here's some a gist of a shell script that does it and announces it via RCON: https://gist.github.com/Bluefissure/b0fcb05c024ee60cad4e23eb55463062

That shell-script is very interesting, thanks for sharing that! ❤️ 👍

**Comment by doodoori2** [comment]
> Here's some a gist of a shell script that does it and announces it via RCON: https://gist.github.com/Bluefissure/b0fcb05c024ee60cad4e23eb55463062

It's a much needed, helpful solution.

**Comment by doodoori2** [comment]
@jammsen 
hi jammsen, 
I Inspired by this thread, I wrote the some code. 

Actually, I'm not very experienced with dockers.
so how did I make a separate repo, I hope this will help

https://github.com/doodoori2/palworld-admin-bashscripts

**Comment by jammsen** [comment]
> @jammsen hi jammsen, I Inspired by this thread, I wrote the some code.
> 
> Actually, I'm not very experienced with dockers. so how did I make a separate repo, I hope this will help
> 
> https://github.com/doodoori2/palworld-admin-bashscripts

I might add something similar too down the line, as you can see we have very creative FR open in here.

**Comment by dakeeper** [comment]
Any updates?

**Comment by keskydi** [comment]
for those interrested, you can use the following configuration in docker-compose. I hadded a limit on the ram usage to auto kill the container if too much ram is used, then always restart the container
```yml
version: '3.9'
services:
  palworld-dedicated-server:
    #build: .
    container_name: palworld-dedicated-server
    image: jammsen/palworld-dedicated-server:latest
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 11gb
      restart_policy:
        condition: any
    ports:
      - target: 8211 # Gamerserver port inside of the container
        published: 8211 # Gamerserver port on your host
        protocol: udp
        mode: host
      - target: 25575 # RCON port inside of the container
        published: 25575 # RCON port on your host
        protocol: tcp
        mode: host
    env_file:
      - ./default.env
    volumes:
      - ./game:/palworld
```
