### ISSUE TITLE
[Bug Report / Configuration] RCON Timeout [Resolved]

### ISSUE THREAD

**Issue by newenpoi** [jammsen/docker-palworld-dedicated-server#77]
### Have you read the Important information text above

- [X] Yes i did

### Current behavior

Might be more a misconfiguration than a bug and please excuse me if it is so,

While running `docker compose run --rm rcon info`
I get the following result `cli: execute: auth: rcon: dial tcp 10.0.0.5:25575: i/o timeout`

### Desired behavior

It should output the description set at the environment variable SERVER_DESCRIPTION, like in the given example on the readme `Welcome to Pal Server[v0.1.2.0] jammsen-docker-generated-20384`.

### Links to screenshots

![image](https://github.com/jammsen/docker-palworld-dedicated-server/assets/58981019/5b213609-229c-4904-9f3c-2c54751c6a11)

### To Reproduce

I used the default docker compose given as in the example, only the **published** port for the dedicated server (not rcon) has been modified to 7777, the rest is basically the same.

I also tried to switch between RCON_ENABLED True & False, it was False by default, no changes.

I tried to edit this line `entrypoint: ['/rcon', '-a', '10.0.0.5:25575', '-p', 'passwd']` (with the corresponding password from the dedicated server of course), by using palworld-dedicated-server:25575 instead, no changes.

### Software setup

- OS: Windows 11
- Docker: 4.26.1 (Docker Desktop)

### Hardware setup

Enough power to fry my whole building I guess... 😆

**Comment by jammsen** [comment]
Hello @newenpoi - Please remove my testing ip 10.0.0.5 and update it with your docker-node ip 😄

**Comment by WJSGDBZ** [comment]
I meet the same thing， but I modify the line
 `
entrypoint: ['/rcon', '-a', '127.0.0.1:25575', '-p', 'palworldadmin']
` 
but also notify 
**cli: execute: auth: rcon: dial tcp 127.0.0.1:25575: connect: connection refused**

**Comment by jammsen** [comment]
Do you have Discord? Can you add me and we jump in a call please? Nickname jammsen

**Comment by newenpoi** [comment]
Thank you for your reply @jammsen , I just recently started using with Docker, so the term `docker-node ip` is not very relevant to me yet, however, I suppose you meant this line `"IPAddress": "172.17.0.2"` when doing a docker inspect on the container?

Please correct me if I am wrong, also, I added you on discord. 😆

**Comment by Ignoto95** [comment]
> Thank you for your reply @jammsen , I just recently started using Docker, so the term `docker-node ip` is not very relevant to me yet, however, I suppose you meant this line `"IPAddress": "172.17.0.2"` when doing a docker inspect on the container?
> 
> Please correct me if I am wrong, also, I added you on discord. 😆

Yes, also you can use "ip addr show docker0" for view the ip address of docker and use that! change the docker-compose.yml and you can re-run command. GLHF

**Comment by newenpoi** [comment]
Thank you for your suggestion @Ignoto95 , but on Windows 11, this issue is resolved by using this line for example `entrypoint: ['/rcon', '-a', '192.168.1.21:25573', '-p', 'passwd']` instead of `entrypoint: ['/rcon', '-a', '127.0.0.1:25573', '-p', 'passwd']`.
Seems like docker on W11 didn't liked the loopback (:

Thanks for your time @jammsen !

**Comment by kdaye** [comment]
pls help, I have not idea about this issue.`cli: execute: auth: rcon: dial tcp 127.17.0.2:25575: connect: connection refused`

docker-compose.yml
```
version: '3.9'
services:
  palworld:
    container_name: palworld
    image: jammsen/palworld-dedicated-server:latest
    restart: always
    network_mode: bridge
    ports:
      - target: 8211 # gamerserver port inside of the container
        published: 8211 # gamerserver port on your host
        protocol: udp
        mode: host
      - target: 25575 # rcon port inside of the container
        published: 25575 # rcon port on your host
        protocol: tcp
        mode: host
    environment:
      - PGID=1000
      - PUID=1000
      - ALWAYS_UPDATE_ON_START=true
      - MAX_PLAYERS=32
      - MULTITHREAD_ENABLED=true
      - COMMUNITY_SERVER=true
      - RCON_ENABLED=true
      - RCON_PORT=25575
      - PUBLIC_IP=
      - PUBLIC_PORT=8211
      - SERVER_NAME=PalWorld
      - SERVER_DESCRIPTION="PalWorld"
      - SERVER_PASSWORD=
      - ADMIN_PASSWORD=adminpaswd
      - BACKUP_ENABLED=true
      - BACKUP_CRON_EXPRESSION=0 * * * *
      - COLLECTION_DROP_RATE=5.000000
      - ENEMY_DROP_ITEM_RATE=5.000000
      - DEATH_PENALTY=None
      - PAL_EGG_DEFAULT_HATCHING_TIME=0.000001
      - NIGHTTIME_SPEEDRATE=0.300000
      - EXP_RATE=1.000000
    volumes:
      - ./game:/palworld

  rcon:
    image: outdead/rcon:latest
    entrypoint: ['/rcon', '-a', '127.17.0.2:25575', '-p', 'adminpaswd']
    profiles: ['rcon']

```
docker inspect palworld
``
"IPAddress": "172.17.0.2",
``

```
$ip addr show docker0
5: docker0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:a3:f2:48:4d brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fd00::1/80 scope global 
       valid_lft forever preferred_lft forever
    inet6 fe80::42:a3ff:fef2:484d/64 scope link proto kernel_ll 
       valid_lft forever preferred_lft forever
    inet6 fe80::1/64 scope link 
       valid_lft forever preferred_lft forever
```
issue
```
[root@archlinux PalServer]# docker compose run --rm rcon info
cli: execute: auth: rcon: dial tcp 127.17.0.2:25575: connect: connection refused
```

Thanks everyone.
